# Generated by Django 5.2.16 on 2026-08-08 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitestaff',
            name='accepted_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodapp.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodapp.table'),
        ),
        migrations.AlterField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodapp.invitestaff'),
        ),
        migrations.AlterField(
            model_name='table',
            name='state',
            field=models.CharField(choices=[('occupied', 'Occupied'), ('available', 'Available'), ('cleaning', 'Cleaning'), ('reserved', 'Reserved')], default='cleaning', max_length=50),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('reslove', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.customer')),
                ('resturant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.resturant')),
            ],
        ),
    ]
