# Generated by Django 5.2.16 on 2026-08-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodapp", "0003_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="point",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
