# Generated by Django 5.2.16 on 2026-08-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodapp", "0004_alter_customer_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitestaff",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invitestaff",
            name="expiring",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
