# Generated by Django 5.2.16 on 2026-08-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodapp", "0005_alter_invitestaff_accepted_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="is_avaiable",
            new_name="is_available",
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu/"),
        ),
    ]
