# Generated by Django 5.2.16 on 2026-08-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodapp", "0006_rename_is_avaiable_menuitem_is_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="resolution",
            field=models.TextField(blank=True, null=True),
        ),
    ]
